from invyra_forecasting.services.intelligence_forecasting import run_item_forecast_with_registry_intelligence


def test_registry_intelligence_helper_remains_importable_after_explanation_enrichment():
    assert callable(run_item_forecast_with_registry_intelligence)
    assert run_item_forecast_with_registry_intelligence.__name__ == "run_item_forecast_with_registry_intelligence"
